### ISSUE TITLE
Task exception was never retrieved: ConnectionRefusedError

### ISSUE THREAD

**Issue by ItsEcholot** [ItsEcholot/real-stereo-extended#24]
The following exception occurs when adding the master node and assigning it to a room. Interestingly the config file gets correctly updated. But because of the exception no `Acknowledgement` gets sent to the client so the exception isn't visible to the user at all and it appears to be _loading_ indefinitely.

Is this maybe because the master tries to update the slave but this fails because the master itself is the slave in this instance?

```python
Task exception was never retrieved
future: <Task finished name='Task-60' coro=<AsyncServer._handle_event_internal() done, defined at /workspaces/real-stereo-extended/backend/.venv/lib/python3.9/site-packages/socketio/asyncio_server.py:492> exception=ConnectionRefusedError(111, 'Connection refused')>
Traceback (most recent call last):
  File "/workspaces/real-stereo-extended/backend/.venv/lib/python3.9/site-packages/socketio/asyncio_server.py", line 494, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/workspaces/real-stereo-extended/backend/.venv/lib/python3.9/site-packages/socketio/asyncio_server.py", line 530, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/workspaces/real-stereo-extended/backend/.venv/lib/python3.9/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "/workspaces/real-stereo-extended/backend/src/api/controllers/nodes.py", line 100, in on_update
    self.config.node_repository.call_listeners()
  File "/workspaces/real-stereo-extended/backend/src/repositories/repository.py", line 20, in call_listeners
    listener()
  File "/workspaces/real-stereo-extended/backend/src/protocol/master/node_registry.py", line 54, in update_acquisition_status
    self.master.send_acquisition(node.ip_address)
  File "/workspaces/real-stereo-extended/backend/src/protocol/master/master.py", line 85, in send_acquisition
    self.get_slave_socket(address).sendall(message.SerializeToString())
  File "/workspaces/real-stereo-extended/backend/src/protocol/master/master.py", line 48, in get_slave_socket
    slave_socket.connect((address, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by cyrilwanner** [comment]
Sorry, that somehow slipped through my tests.
Yes, I think your assumption is correct. The master should never open a connection to himself (there isn't even a TCP socket listening). I'll fix it quickly 👍
