### ISSUE TITLE
Room calibration throws errors

### ISSUE THREAD

**Issue by cyrilwanner** [ItsEcholot/real-stereo-extended#75]
When I try to start the calibration for a new room and click on "Next position" for the first time, the following errors get thrown and the real-stereo process crashes. (I was successfully detected in both cameras, so that can't be the reason)

```
task: <Task finished coro=<RequestHandler._handle_request() done, defined at /home/pi/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py:413> exception=RuntimeError('Missing return statement on request handler')>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/real-stereo-extended/backend/src/__main__.py", line 39, in main
    networking.initial_check(),
  File "/home/pi/real-stereo-extended/backend/src/balancing/manager.py", line 40, in start_control
    await self.sonos.control_loop()
  File "/home/pi/real-stereo-extended/backend/src/balancing/sonos.py", line 58, in control_loop
    command.run(self.sonos_adapter)
  File "/home/pi/real-stereo-extended/backend/src/balancing/sonos_command.py", line 56, in run
    sonos_adapter.play_calibration_sound(speaker)
  File "/home/pi/real-stereo-extended/backend/src/sonos/adapter_soco.py", line 79, in play_calibration_sound
    soco_instance.play_uri(uri=self.calibration_sound_uri, title='RS Calibration Sound')
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 122, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 706, in play_uri
    return self.play()
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 122, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 620, in play
    self.avTransport.Play([("InstanceID", 0), ("Speed", 1)])
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 503, in send_command
    self.handle_upnp_error(response.text)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 562, in handle_upnp_error
    error_xml=xml_error,
soco.exceptions.SoCoUPnPException: UPnP Error 701 received: Transition not available from 192.168.1.73
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 580, in finish_response
    prepare_meth = resp.prepare
AttributeError: 'NoneType' object has no attribute 'prepare'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 485, in start
    resp, reset = await task
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 440, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/home/pi/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 583, in finish_response
    raise RuntimeError("Missing return " "statement on request handler")
RuntimeError: Missing return statement on request handler
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/real-stereo-extended/backend/src/__main__.py", line 63, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/pi/real-stereo-extended/backend/src/__main__.py", line 39, in main
    networking.initial_check(),
  File "/home/pi/real-stereo-extended/backend/src/balancing/manager.py", line 40, in start_control
    await self.sonos.control_loop()
  File "/home/pi/real-stereo-extended/backend/src/balancing/sonos.py", line 58, in control_loop
    command.run(self.sonos_adapter)
  File "/home/pi/real-stereo-extended/backend/src/balancing/sonos_command.py", line 56, in run
    sonos_adapter.play_calibration_sound(speaker)
  File "/home/pi/real-stereo-extended/backend/src/sonos/adapter_soco.py", line 79, in play_calibration_sound
    soco_instance.play_uri(uri=self.calibration_sound_uri, title='RS Calibration Sound')
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 122, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 706, in play_uri
    return self.play()
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 122, in inner_function
    return function(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/core.py", line 620, in play
    self.avTransport.Play([("InstanceID", 0), ("Speed", 1)])
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 207, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 503, in send_command
    self.handle_upnp_error(response.text)
  File "/home/pi/.local/lib/python3.7/site-packages/soco/services.py", line 562, in handle_upnp_error
    error_xml=xml_error,
soco.exceptions.SoCoUPnPException: UPnP Error 701 received: Transition not available from 192.168.1.73
```

Did you experience something similar to this or have an idea why this could happen?

**Comment by ItsEcholot** [comment]
This could be related to the automatic grouping of the speakers we do before room calibration... I didn't experience this myself to be honest. How were your speakers setup? Stereo or two single units? If single, were they grouped together or separate?

**Comment by cyrilwanner** [comment]
They are set up in a stereo pair. I didn't change anything since the last calibration that worked. But I now also tried to set them up as two separate single units, but without any success. Also unplugging them from the power and start them again does not help.

If I search for this UPnP error, I get results that something gets performed in a state that is not possible (like pause when it is already paused). Does calibration still work for you on the main branch? I'm not sure if a recent change has introduced this, but I'll try to further debug it.

**Comment by ItsEcholot** [comment]
I have mine setup as two single units and calibration works fine for me, this is really weird...

**Comment by cyrilwanner** [comment]
I just figured it out, somehow the calibration sound URL is set to `http://127.0.0.1:8079/backend-assets/white_noise.mp3` which of course does not make sense. It may be that it is related to a change in the ad hoc setup (the hostname is added to the /etc/hosts file pointing to 127.0.0.1). I'll open a PR when I have a solution for this.
